module.exports = {
    vi: [
        //9
        "su-ong-lang-mai--tang-than-dich-thuc",
        "thay-phap-niem--tieng-cuoi-tre-da-vang",
        "su-co-thoai-nghiem--mot-dong-xanh-biec",
        "su-co-hoa-nghiem--nep-xua",
        "thay-phap-dung--tieng-chuong-chanh-niem",
        //8 Thầy ôm các con vào lòng	Sc. Sùng N
        // "su-co-sung-nghiem--thay-om-cac-vao-long",
        "thay-phap-an--thap-len-ngon-nen",
        //10 Ngàn xưa hẹn trở về	Thầy Nguyên Tịnh
        // "thay-nguyen-tinh--ngan-xua-hen-tro-ve",
        "su-co-doan-nghiem--thuong-nhu-thay-thuong",
        "thay-phap-nguyen--que-me-van-toa-ngat-huong-thom",
        "thay-minh-hy--bua-tiec-cua-nguoi-tu",
        "thay-phap-kham--cham-soc-tang-than",
        "thay-phap-hoi--theo-thay-lam-bao",
        "su-co-trang-bo-de--advent",
        //20 Thấy Thầy trong tăng thân	Sr. Chân Đức
        "su-co-chan-duc--thay-thay-trong-tang-than",
        //22 Niềm thương bình an	Sr. Tuyết N
        // "su-co-tuyet-nghiem--niem-thuong-binh-an",
        "thay-troi-dao-bi--da-co-duong-di-roi-con-khong-con-lo-so",
        "su-co-chuan-nghiem--thuong-yeu-muon-doi-van-hat-suong-trong",
        "thay-troi-dai-dao--chung-tay-giu-gin-dat-me",
        "su-co-trang-mai-thon--nhap-luu-ngay-binh-thuong",
        "su-co-thao-nghiem--rong-choi-ngay-nang-day",
        "su-co-boi-nghiem--cam-di",
        "su-co-thuan-khanh--duoi-chan-ngon-hung-phong",
        "thay-phap-ung--con-ga-va-qua-trung",
        //38 Giấc mơ đại đồng	Chân Thu Lâm - Minh Hương
        "minh-huong--giac-mo-dai-dong",
        //39 su-co-hoc-nghiem--cuoc-doi-thay-rat-dep.md
        "su-co-sac-nghiem--khi-tiep-nhan-cung-trao-truyen",
        //46 Cuộc đời Thầy rất đẹp	Sr. Học N
        "su-co-hoc-nghiem--cuoc-doi-thay-rat-dep",
        "su-co-hoi-nghiem--thoi-gian-la-su-song",
        "thay-phap-kha--quan-tam",
        //63
        "lang-mai-nam-qua",
    ],
    en: [
        "su-ong--the-true-sangha",
        "tributes-to-thay",
        "thank-you-thay",
        "disciples-pv-eulogy",
        "disciples-vi-eulogy",
        "sr-chan-duc--returning-to-lower-hamlet",
        "br-minh-hy--dharma-banquet",
        "br-phap-an--light-up-a-candle",
        "sr-thuan-khanh--at-the-foot-of-the-majestic-mountain",
        "br-phap-kham--taking-care-of-the-sangha",
        "sr-thoai-nghiem--the-emerald-stream-flows-on",
        "br-nguyen-tinh--a-thousand-years-of-returning",
        "br-phap-dung--bells-of-mindfulness",
        "br-phap-luu--thays-vision-for-wake-up-schools",
        "br-phap-hai--don-t-cover-over-your-monastic-life-with-bells-and-incense",
        "br-phap-linh--two-leaves-at-the-tip-of-the-branch",
        "br-phap-niem--the-laughter-of-children-echoes",
        "br-phap-ung--chicken-and-egg",
        "br-troi-bao-tang--engaging-suffering-in-the-present-moment",
        "br-troi-dai-dao--the-environment-what-can-we-do",
        "br-troi-dao-bi--you-have-seen-the-path-do-not-fear-anymore",
        "br-troi-dao-quang--are-1-000-buddhas-enough",
        "br-troi-duc-hien--all-is-joy",
        "br-troi-duc-niem--i-have-a-dream",
        "br-troi-ruong-duc--happiness-where-are-you",
        "br-troi-thien-chi--mirror-mirror-on-the-wall",
        "br-phap-hoi--working-on-the-tet-times",
        "dharmacharya-shantum-seth--my-teacher-my-friend",
        "dr-elli-weisbaum--healing-the-healers",
        "hisae-matsuda-and-terry-barber--parallax-press-and-the-journey-to-plum-village-through-books",
        "richard-brady--free-at-school",
        "sr-dieu-nghiem-jina-and-sr-tu-nghiem-eleni--celebrating-life",
        "sr-doan-nghiem--with-time-everything-transforms",
        "sr-giac-nghiem--peace-and-happiness-walk-hand-in-hand",
        "sr-hoa-nghiem--a-box-of-lu-biscuits",
        "sr-thao-nghiem--strolling-with-joy-on-a-sunny-day",
        "sr-trang-bo-de--advent-preserving-a-beautiful-tradition",
        "sr-trang-chanh-niem--poems",
        "sr-trang-hien-nhan--hello-attachment-you-are-my-friend",
        "sr-trang-tam-muoi--no-escape-retreat",
        "sr-tue-nghiem--safe-harbor",
        "sr-tu-nghiem--poems",
        "sr-trang-mai-thon--collecting-gum-nuts",
        "br-phap-luu--thays-vision-for-wake-up-schools",]
};
