module.exports = {
    vi: [

        //1
        //"Làng Mai Năm Qua"
        //2
        "su-ong-lang-mai--tang-than-dich-thuc",
        //3
        "thay-chan-phap-niem--tieng-cuoi-tre-da-vang",
        //4
        //5
        "su-co-chan-hoa-nghiem--nep-xua",
        //6
        "thay-chan-phap-dung--giac-mo-cua-thay",
        //7
        //8
        //9
        "thay-chan-phap-an--thap-len-ngon-nen",
        //10
        //11
        "su-co-doan-nghiem--thuong-nhu-thay-thuong",
        //12
        //13
        "thay-chan-phap-nguyen--que-me-van-toa-ngat-huong-thom",
        //14
        "thay-chan-minh-hy--bua-tiec-cua-nguoi-tu",
        //15
        "thay-chan-phap-kham--cham-soc-tang-than",
        //16
        //17
        "thay-chan-phap-hoi--theo-thay-lam-bao",
        //18
        //19
        "su-co-chan-trang-bo-de--advent",
        //20
        "su-co-chan-duc--tro-ve-xom-ha",
        //21
        //22
        //23
        "thay-chan-troi-dao-bi--da-co-duong-di-roi-con-khong-con-lo-so",
        //24
        //25
        //26
        "su-co-chan-chuan-nghiem--thuong-yeu-muon-doi-van-hat-suong-trong",
        //27
        "thay-chan-troi-dai-dao--chung-tay-giu-gin-dat-me",
        //28
        "su-co-trang-mai-thon--nhap-luu-ngay-binh-thuong",
        //29
        //30
        //31
        "su-co-chan-thao-nghiem--rong-choi-ngay-nang-day",
        //32
        "su-co-chan-boi-nghiem--cam-di",
        //33
        //34
        //35
        //36
        //37
        //38
        //39
        //40
        //41
        //42
        //43
        //44
        //45
        //46
        //47
        //48
        //49
        "su-co-chan-hoi-nghiem--thoi-gian-la-su-song",
        //50
        //51
        //52
        //53
        //54
    ],
};
