module.exports = {
    vi: [
        //1
        "lang-mai-nam-qua",
        //2
        "su-ong-lang-mai--tang-than-dich-thuc",
        //3
        "thay-chan-phap-niem--tieng-cuoi-tre-da-vang",
        //4
        "su-co-chan-thoai-nghiem--mot-dong-xanh-biec",
        //5
        "su-co-chan-hoa-nghiem--nep-xua",
        //6
        "thay-chan-phap-dung--tieng-chuong-chanh-niem",
        //7
        //8 Thầy ôm các con vào lòng	Sc. Sùng N
        // "su-co-sung-nghiem--thay-om-cac-vao-long",
        //9
        "thay-chan-phap-an--thap-len-ngon-nen",
        //10 Ngàn xưa hẹn trở về	Thầy Nguyên Tịnh 
        // "thay-nguyen-tinh--ngan-xua-hen-tro-ve",
        //11
        "su-co-doan-nghiem--thuong-nhu-thay-thuong",
        //12
        //13
        "thay-chan-phap-nguyen--que-me-van-toa-ngat-huong-thom",
        //14
        "thay-chan-minh-hy--bua-tiec-cua-nguoi-tu",
        //15
        "thay-chan-phap-kham--cham-soc-tang-than",
        //16
        //17
        "thay-chan-phap-hoi--theo-thay-lam-bao",
        //18
        //19
        "su-co-chan-trang-bo-de--advent",
        //20 Thấy Thầy trong tăng thân	Sr. Chân Đức
        // OLD: "su-co-chan-duc--tro-ve-xom-ha",
        "su-co-chan-duc--thay-thay-trong-tang-than",
        //21
        //22 Niềm thương bình an	Sr. Tuyết N
        // "su-co-tuyet-nghiem--niem-thuong-binh-an",
        //23
        "thay-chan-troi-dao-bi--da-co-duong-di-roi-con-khong-con-lo-so",
        //24
        //25
        //26
        "su-co-chan-chuan-nghiem--thuong-yeu-muon-doi-van-hat-suong-trong",
        //27
        "thay-chan-troi-dai-dao--chung-tay-giu-gin-dat-me",
        //28
        "su-co-trang-mai-thon--nhap-luu-ngay-binh-thuong",
        //29
        //30
        //31
        "su-co-chan-thao-nghiem--rong-choi-ngay-nang-day",
        //32
        "su-co-chan-boi-nghiem--cam-di",
        //33
        //34
        "su-co-chan-thuan-khanh--duoi-chan-ngon-hung-phong",
        //35
        //36
        "thay-chan-phap-ung--con-ga-va-qua-trung",
        //37
        //38 Giấc mơ đại đồng	Chân Thu Lâm - Minh Hương
        // "minh-huong--giac-mo-dai-dong",
        //39
        //40
        //41
        //42
        //43
        "su-co-chan-sac-nghiem--khi-tiep-nhan-cung-trao-truyen",
        //44
        //45
        //46
        //47
        //48
        //49
        "su-co-chan-hoi-nghiem--thoi-gian-la-su-song",
        //50
        //51
        //52
        "thay-chan-phap-kha--quan-tam",
        //53
        //54
    ],
    en: [
        //1
        "tributes-to-thay",
        "disciples-pv-eulogy",
        "disciples-vi-eulogy",
        "su-ong--the-true-sangha",
        "sister-chan-duc--returning-to-lower-hamlet",
        "brother-chan-minh-hy--dharma-banquet",
        "sister-chan-thuan-khanh--at-the-foot-of-the-majestic-mountain",
        "brother-chan-phap-kham--taking-care-of-the-sangha",
        "sister-chan-thoai-nghiem--the-emerald-stream-flows-on",
        "brother-chan-nguyen-tinh--a-thousand-years-of-returning",
        "brother-chan-phap-dung--bells-of-mindfulness",
        "brother-chan-phap-hai--don-t-cover-over-your-monastic-life-with-bells-and-incense",
        "brother-chan-phap-linh--two-leaves-at-the-tip-of-the-branch",
        "brother-chan-phap-niem--the-laughter-of-children-echoes",
        "brother-chan-phap-ung--chicken-and-egg",
        "brother-chan-troi-bao-tang--engaging-suffering-in-the-present-moment",
        "brother-chan-troi-dai-dao--the-environment-what-can-we-do",
        "brother-chan-troi-dao-bi--you-have-seen-the-path-do-not-fear-anymore",
        "brother-chan-troi-dao-quang--are-1-000-buddhas-enough",
        "brother-chan-troi-duc-hien--all-is-joy",
        "brother-chan-troi-duc-niem--i-have-a-dream",
        "brother-chan-troi-ruong-duc--happiness-where-are-you",
        "brother-chan-troi-thien-chi--mirror-mirror-on-the-wall",
        "brother-phap-hoi--working-on-the-tet-times",
        "dharmacharya-shantum-seth--my-teacher-my-friend",
        "dr-elli-weisbaum--healing-the-healers",
        "hisae-matsuda-and-terry-barber--parallax-press-and-the-journey-to-plum-village-through-books",
        "richard-brady--an-interview-with-richard-brady",
        "sister-chan-dieu-nghiem-jina-and-sister-chan-tu-nghiem-eleni--celebrating-life",
        "sister-chan-doan-nghiem--with-time-everything-transforms",
        "sister-chan-giac-nghiem--peace-and-happiness-walk-hand-in-hand",
        "sister-chan-hoa-nghiem--a-box-of-lu-biscuits",
        "sister-chan-thao-nghiem--strolling-with-joy",
        "sister-chan-trang-bo-de--advent-preserving-a-beautiful-tradition",
        "sister-chan-trang-chanh-niem--poems",
        "sister-chan-trang-hien-nhan--hello-attachment-you-are-my-friend",
        "sister-chan-trang-tam-muoi--no-escape-retreat",
        "sister-chan-tue-nghiem--safe-harbor",
        "sister-chan-tu-nghiem--poems",
        "sister-chan-trang-mai-thon--collecting-gum-nuts",
        //2
        //3
        //4
        //5
        //6
        //7
        //8
        //9
        //10
        //11
        //12
        //13
        //14
        //15
        //16
        //17
        //18
        //19
        //20
        //21
        //22
        //23
        //24
        //25
        //26
        //27
        //28
        //29
        //30
        //31
        //32
        //33
        //34
        //35
        //36
        //37
        //38
        //39
        //40
        //41
        //42
        //43
        //44
    ]
};
